# Generated by Django 3.2.9 on 2022-04-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhelkayWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phelkay_word', models.CharField(max_length=255)),
                ('p_phrase', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ZhebsaWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhebsa_word', models.CharField(max_length=255)),
                ('z_phrase', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
                ('phelkay', models.ManyToManyField(to='webapp.PhelkayWord')),
            ],
        ),
    ]
