# Generated by Django 3.2.9 on 2022-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhebsaword',
            name='audio',
            field=models.FileField(null=True, upload_to='document/'),
        ),
    ]
