# Generated by Django 3.2.9 on 2022-04-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_zhebsaword_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhebsaword',
            name='audio',
        ),
        migrations.AddField(
            model_name='zhebsaword',
            name='zhebsa_pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
