# Generated by Django 3.2.9 on 2022-04-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_contactdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zhebsaword',
            old_name='zhebsa_pronunciation',
            new_name='audio',
        ),
    ]
