# Generated by Django 3.2.9 on 2022-04-30 12:15

from django.db import migrations, models
import webapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_phelkayword_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phelkayword',
            options={'ordering': ['phelkay_word']},
        ),
        migrations.AlterModelOptions(
            name='zhebsaword',
            options={'ordering': ['zhebsa_word']},
        ),
        migrations.AlterField(
            model_name='phelkayword',
            name='phelkay_word',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='zhebsaword',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=webapp.storage.OverwriteStorage(), upload_to='zhesaAudio/'),
        ),
        migrations.AlterField(
            model_name='zhebsaword',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zhebsaword',
            name='zhebsa_word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
