# Generated by Django 3.2.9 on 2022-05-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_contactdetails_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phelkayword',
            name='p_phrase',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zhebsaword',
            name='z_phrase',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
