# Generated by Django 3.2.9 on 2022-05-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20220501_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phelkayword',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zhebsaword',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
