# Generated by Django 3.2.9 on 2022-05-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_zhebsaword_phelkay'),
        ('webapp', '0014_auto_20220501_1734'),
    ]

    operations = [
    ]
